# Generated by Django 4.2.6 on 2023-11-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
