# Generated by Django 4.2.6 on 2023-11-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_pictures/'),
        ),
    ]
