# Generated by Django 4.2.6 on 2023-11-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='please',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='major',
            name='please',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
