# Generated by Django 4.2.6 on 2023-11-07 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='tutored_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TutorApp.class'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='major',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TutorApp.major'),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='TutorApp.student'),
        ),
        migrations.AlterField(
            model_name='session',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='TutorApp.tutor'),
        ),
    ]
