# Generated by Django 4.2.6 on 2023-11-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0002_major_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='major',
            name='abbreviation',
            field=models.CharField(default='placeholder', max_length=20),
        ),
    ]
