# Generated by Django 4.2.6 on 2023-11-10 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0002_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoringsession',
            name='date',
        ),
        migrations.AlterField(
            model_name='tutoringsession',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tutoringsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
