# Generated by Django 4.2.6 on 2023-11-10 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0003_remove_tutoringsession_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoringsession',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='TutorApp.student'),
        ),
    ]
