# Generated by Django 4.2.6 on 2023-11-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0004_alter_tutoringsession_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
