# Generated by Django 4.2.6 on 2023-11-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0005_tutoringsession_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoringsession',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='TutorApp.shift'),
        ),
    ]
