# Generated by Django 4.2.6 on 2023-11-12 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0006_tutoringsession_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
