# Generated by Django 4.2.6 on 2023-11-12 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TutorApp', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='TutorApp.tutor'),
        ),
    ]
